# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soulfire/api_docs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'soulfire/api_docs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17soulfire/api_docs.proto\x12\x0bsoulfire.v1\x1a google/protobuf/descriptor.proto\"\xd3\x02\n\rApiMethodDocs\x12!\n\x0c\x64isplay_name\x18\x01 \x01(\tR\x0b\x64isplayName\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12 \n\x0bpermissions\x18\x03 \x03(\tR\x0bpermissions\x12\x14\n\x05scope\x18\x04 \x01(\tR\x05scope\x12$\n\rpreconditions\x18\x05 \x03(\tR\rpreconditions\x12\x1c\n\texecution\x18\x06 \x01(\tR\texecution\x12!\n\x0cside_effects\x18\x07 \x03(\tR\x0bsideEffects\x12\"\n\rexpose_to_mcp\x18\x08 \x01(\x08R\x0b\x65xposeToMcp\x12:\n\x19mcp_requires_confirmation\x18\t \x01(\x08R\x17mcpRequiresConfirmation\"@\n\x0c\x41piFieldDocs\x12\x16\n\x06\x66ormat\x18\x01 \x01(\tR\x06\x66ormat\x12\x18\n\x07\x65xample\x18\x02 \x01(\tR\x07\x65xample:[\n\napi_method\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x01(\x0b\x32\x1a.soulfire.v1.ApiMethodDocsR\tapiMethod:W\n\tapi_field\x12\x1d.google.protobuf.FieldOptions\x18\xba\x8e\x03 \x01(\x0b\x32\x19.soulfire.v1.ApiFieldDocsR\x08\x61piFieldB/\n\x1d\x63om.soulfiremc.grpc.generatedB\x0c\x41piDocsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soulfire.api_docs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.soulfiremc.grpc.generatedB\014ApiDocsProtoP\001'
  _globals['_APIMETHODDOCS']._serialized_start=75
  _globals['_APIMETHODDOCS']._serialized_end=414
  _globals['_APIFIELDDOCS']._serialized_start=416
  _globals['_APIFIELDDOCS']._serialized_end=480
# @@protoc_insertion_point(module_scope)
