# Generated from soulfire/bot_live.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .bot_live_pb2 import AcquireBotControlRequest, AcquireBotControlResponse, AttackEntityRequest, AttackEntityResponse, BotEvent, DigBlockRequest, DigBlockResponse, FindBlocksRequest, FindBlocksResponse, GetBlockRequest, GetBlockResponse, GoToRequest, InteractEntityRequest, InteractEntityResponse, ListNearbyEntitiesRequest, ListNearbyEntitiesResponse, PathfindProgress, PlaceBlockRequest, PlaceBlockResponse, ReleaseBotControlRequest, ReleaseBotControlResponse, ReleaseItemRequest, ReleaseItemResponse, RenewBotControlRequest, RenewBotControlResponse, RespawnRequest, RespawnResponse, SendChatRequest, SendChatResponse, StopPathfindingRequest, StopPathfindingResponse, SwingArmRequest, SwingArmResponse, UseItemRequest, UseItemResponse, WatchBotEventsRequest

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class BotLiveService(Protocol):
    def watch_bot_events(self, request: WatchBotEventsRequest, ctx: RequestContext[WatchBotEventsRequest, BotEvent]) -> AsyncIterator[BotEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def send_chat(self, request: SendChatRequest, ctx: RequestContext[SendChatRequest, SendChatResponse]) -> SendChatResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_block(self, request: GetBlockRequest, ctx: RequestContext[GetBlockRequest, GetBlockResponse]) -> GetBlockResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def find_blocks(self, request: FindBlocksRequest, ctx: RequestContext[FindBlocksRequest, FindBlocksResponse]) -> FindBlocksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_nearby_entities(self, request: ListNearbyEntitiesRequest, ctx: RequestContext[ListNearbyEntitiesRequest, ListNearbyEntitiesResponse]) -> ListNearbyEntitiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def dig_block(self, request: DigBlockRequest, ctx: RequestContext[DigBlockRequest, DigBlockResponse]) -> DigBlockResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def place_block(self, request: PlaceBlockRequest, ctx: RequestContext[PlaceBlockRequest, PlaceBlockResponse]) -> PlaceBlockResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def use_item(self, request: UseItemRequest, ctx: RequestContext[UseItemRequest, UseItemResponse]) -> UseItemResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def release_item(self, request: ReleaseItemRequest, ctx: RequestContext[ReleaseItemRequest, ReleaseItemResponse]) -> ReleaseItemResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def attack_entity(self, request: AttackEntityRequest, ctx: RequestContext[AttackEntityRequest, AttackEntityResponse]) -> AttackEntityResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def interact_entity(self, request: InteractEntityRequest, ctx: RequestContext[InteractEntityRequest, InteractEntityResponse]) -> InteractEntityResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def swing_arm(self, request: SwingArmRequest, ctx: RequestContext[SwingArmRequest, SwingArmResponse]) -> SwingArmResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def respawn(self, request: RespawnRequest, ctx: RequestContext[RespawnRequest, RespawnResponse]) -> RespawnResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def go_to(self, request: GoToRequest, ctx: RequestContext[GoToRequest, PathfindProgress]) -> AsyncIterator[PathfindProgress]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def stop_pathfinding(self, request: StopPathfindingRequest, ctx: RequestContext[StopPathfindingRequest, StopPathfindingResponse]) -> StopPathfindingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def acquire_bot_control(self, request: AcquireBotControlRequest, ctx: RequestContext[AcquireBotControlRequest, AcquireBotControlResponse]) -> AcquireBotControlResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def renew_bot_control(self, request: RenewBotControlRequest, ctx: RequestContext[RenewBotControlRequest, RenewBotControlResponse]) -> RenewBotControlResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def release_bot_control(self, request: ReleaseBotControlRequest, ctx: RequestContext[ReleaseBotControlRequest, ReleaseBotControlResponse]) -> ReleaseBotControlResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class BotLiveServiceASGIApplication(ConnectASGIApplication[BotLiveService]):
    def __init__(
        self,
        service: BotLiveService | AsyncGenerator[BotLiveService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/soulfire.v1.BotLiveService/WatchBotEvents": Endpoint.server_stream(
                    method=MethodInfo(
                        name="WatchBotEvents",
                        service_name="soulfire.v1.BotLiveService",
                        input=WatchBotEventsRequest,
                        output=BotEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch_bot_events,
                ),
                "/soulfire.v1.BotLiveService/SendChat": Endpoint.unary(
                    method=MethodInfo(
                        name="SendChat",
                        service_name="soulfire.v1.BotLiveService",
                        input=SendChatRequest,
                        output=SendChatResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.send_chat,
                ),
                "/soulfire.v1.BotLiveService/GetBlock": Endpoint.unary(
                    method=MethodInfo(
                        name="GetBlock",
                        service_name="soulfire.v1.BotLiveService",
                        input=GetBlockRequest,
                        output=GetBlockResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_block,
                ),
                "/soulfire.v1.BotLiveService/FindBlocks": Endpoint.unary(
                    method=MethodInfo(
                        name="FindBlocks",
                        service_name="soulfire.v1.BotLiveService",
                        input=FindBlocksRequest,
                        output=FindBlocksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.find_blocks,
                ),
                "/soulfire.v1.BotLiveService/ListNearbyEntities": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNearbyEntities",
                        service_name="soulfire.v1.BotLiveService",
                        input=ListNearbyEntitiesRequest,
                        output=ListNearbyEntitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_nearby_entities,
                ),
                "/soulfire.v1.BotLiveService/DigBlock": Endpoint.unary(
                    method=MethodInfo(
                        name="DigBlock",
                        service_name="soulfire.v1.BotLiveService",
                        input=DigBlockRequest,
                        output=DigBlockResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.dig_block,
                ),
                "/soulfire.v1.BotLiveService/PlaceBlock": Endpoint.unary(
                    method=MethodInfo(
                        name="PlaceBlock",
                        service_name="soulfire.v1.BotLiveService",
                        input=PlaceBlockRequest,
                        output=PlaceBlockResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.place_block,
                ),
                "/soulfire.v1.BotLiveService/UseItem": Endpoint.unary(
                    method=MethodInfo(
                        name="UseItem",
                        service_name="soulfire.v1.BotLiveService",
                        input=UseItemRequest,
                        output=UseItemResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.use_item,
                ),
                "/soulfire.v1.BotLiveService/ReleaseItem": Endpoint.unary(
                    method=MethodInfo(
                        name="ReleaseItem",
                        service_name="soulfire.v1.BotLiveService",
                        input=ReleaseItemRequest,
                        output=ReleaseItemResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.release_item,
                ),
                "/soulfire.v1.BotLiveService/AttackEntity": Endpoint.unary(
                    method=MethodInfo(
                        name="AttackEntity",
                        service_name="soulfire.v1.BotLiveService",
                        input=AttackEntityRequest,
                        output=AttackEntityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.attack_entity,
                ),
                "/soulfire.v1.BotLiveService/InteractEntity": Endpoint.unary(
                    method=MethodInfo(
                        name="InteractEntity",
                        service_name="soulfire.v1.BotLiveService",
                        input=InteractEntityRequest,
                        output=InteractEntityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.interact_entity,
                ),
                "/soulfire.v1.BotLiveService/SwingArm": Endpoint.unary(
                    method=MethodInfo(
                        name="SwingArm",
                        service_name="soulfire.v1.BotLiveService",
                        input=SwingArmRequest,
                        output=SwingArmResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.swing_arm,
                ),
                "/soulfire.v1.BotLiveService/Respawn": Endpoint.unary(
                    method=MethodInfo(
                        name="Respawn",
                        service_name="soulfire.v1.BotLiveService",
                        input=RespawnRequest,
                        output=RespawnResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.respawn,
                ),
                "/soulfire.v1.BotLiveService/GoTo": Endpoint.server_stream(
                    method=MethodInfo(
                        name="GoTo",
                        service_name="soulfire.v1.BotLiveService",
                        input=GoToRequest,
                        output=PathfindProgress,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.go_to,
                ),
                "/soulfire.v1.BotLiveService/StopPathfinding": Endpoint.unary(
                    method=MethodInfo(
                        name="StopPathfinding",
                        service_name="soulfire.v1.BotLiveService",
                        input=StopPathfindingRequest,
                        output=StopPathfindingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.stop_pathfinding,
                ),
                "/soulfire.v1.BotLiveService/AcquireBotControl": Endpoint.unary(
                    method=MethodInfo(
                        name="AcquireBotControl",
                        service_name="soulfire.v1.BotLiveService",
                        input=AcquireBotControlRequest,
                        output=AcquireBotControlResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.acquire_bot_control,
                ),
                "/soulfire.v1.BotLiveService/RenewBotControl": Endpoint.unary(
                    method=MethodInfo(
                        name="RenewBotControl",
                        service_name="soulfire.v1.BotLiveService",
                        input=RenewBotControlRequest,
                        output=RenewBotControlResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.renew_bot_control,
                ),
                "/soulfire.v1.BotLiveService/ReleaseBotControl": Endpoint.unary(
                    method=MethodInfo(
                        name="ReleaseBotControl",
                        service_name="soulfire.v1.BotLiveService",
                        input=ReleaseBotControlRequest,
                        output=ReleaseBotControlResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.release_bot_control,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.BotLiveService"


class BotLiveServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def watch_bot_events(
        self,
        request: WatchBotEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[BotEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchBotEvents",
                service_name="soulfire.v1.BotLiveService",
                input=WatchBotEventsRequest,
                output=BotEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def send_chat(
        self,
        request: SendChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SendChatResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendChat",
                service_name="soulfire.v1.BotLiveService",
                input=SendChatRequest,
                output=SendChatResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_block(
        self,
        request: GetBlockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetBlockResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBlock",
                service_name="soulfire.v1.BotLiveService",
                input=GetBlockRequest,
                output=GetBlockResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def find_blocks(
        self,
        request: FindBlocksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> FindBlocksResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FindBlocks",
                service_name="soulfire.v1.BotLiveService",
                input=FindBlocksRequest,
                output=FindBlocksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_nearby_entities(
        self,
        request: ListNearbyEntitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListNearbyEntitiesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNearbyEntities",
                service_name="soulfire.v1.BotLiveService",
                input=ListNearbyEntitiesRequest,
                output=ListNearbyEntitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def dig_block(
        self,
        request: DigBlockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DigBlockResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DigBlock",
                service_name="soulfire.v1.BotLiveService",
                input=DigBlockRequest,
                output=DigBlockResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def place_block(
        self,
        request: PlaceBlockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PlaceBlockResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PlaceBlock",
                service_name="soulfire.v1.BotLiveService",
                input=PlaceBlockRequest,
                output=PlaceBlockResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def use_item(
        self,
        request: UseItemRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> UseItemResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UseItem",
                service_name="soulfire.v1.BotLiveService",
                input=UseItemRequest,
                output=UseItemResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def release_item(
        self,
        request: ReleaseItemRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ReleaseItemResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseItem",
                service_name="soulfire.v1.BotLiveService",
                input=ReleaseItemRequest,
                output=ReleaseItemResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def attack_entity(
        self,
        request: AttackEntityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AttackEntityResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AttackEntity",
                service_name="soulfire.v1.BotLiveService",
                input=AttackEntityRequest,
                output=AttackEntityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def interact_entity(
        self,
        request: InteractEntityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> InteractEntityResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InteractEntity",
                service_name="soulfire.v1.BotLiveService",
                input=InteractEntityRequest,
                output=InteractEntityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def swing_arm(
        self,
        request: SwingArmRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SwingArmResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SwingArm",
                service_name="soulfire.v1.BotLiveService",
                input=SwingArmRequest,
                output=SwingArmResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def respawn(
        self,
        request: RespawnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RespawnResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Respawn",
                service_name="soulfire.v1.BotLiveService",
                input=RespawnRequest,
                output=RespawnResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def go_to(
        self,
        request: GoToRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[PathfindProgress]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GoTo",
                service_name="soulfire.v1.BotLiveService",
                input=GoToRequest,
                output=PathfindProgress,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def stop_pathfinding(
        self,
        request: StopPathfindingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> StopPathfindingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StopPathfinding",
                service_name="soulfire.v1.BotLiveService",
                input=StopPathfindingRequest,
                output=StopPathfindingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def acquire_bot_control(
        self,
        request: AcquireBotControlRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AcquireBotControlResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AcquireBotControl",
                service_name="soulfire.v1.BotLiveService",
                input=AcquireBotControlRequest,
                output=AcquireBotControlResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def renew_bot_control(
        self,
        request: RenewBotControlRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RenewBotControlResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RenewBotControl",
                service_name="soulfire.v1.BotLiveService",
                input=RenewBotControlRequest,
                output=RenewBotControlResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def release_bot_control(
        self,
        request: ReleaseBotControlRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ReleaseBotControlResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseBotControl",
                service_name="soulfire.v1.BotLiveService",
                input=ReleaseBotControlRequest,
                output=ReleaseBotControlResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class BotLiveServiceSync(Protocol):
    def watch_bot_events(self, request: WatchBotEventsRequest, ctx: RequestContext[WatchBotEventsRequest, BotEvent]) -> Iterator[BotEvent]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def send_chat(self, request: SendChatRequest, ctx: RequestContext[SendChatRequest, SendChatResponse]) -> SendChatResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_block(self, request: GetBlockRequest, ctx: RequestContext[GetBlockRequest, GetBlockResponse]) -> GetBlockResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def find_blocks(self, request: FindBlocksRequest, ctx: RequestContext[FindBlocksRequest, FindBlocksResponse]) -> FindBlocksResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_nearby_entities(self, request: ListNearbyEntitiesRequest, ctx: RequestContext[ListNearbyEntitiesRequest, ListNearbyEntitiesResponse]) -> ListNearbyEntitiesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def dig_block(self, request: DigBlockRequest, ctx: RequestContext[DigBlockRequest, DigBlockResponse]) -> DigBlockResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def place_block(self, request: PlaceBlockRequest, ctx: RequestContext[PlaceBlockRequest, PlaceBlockResponse]) -> PlaceBlockResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def use_item(self, request: UseItemRequest, ctx: RequestContext[UseItemRequest, UseItemResponse]) -> UseItemResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def release_item(self, request: ReleaseItemRequest, ctx: RequestContext[ReleaseItemRequest, ReleaseItemResponse]) -> ReleaseItemResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def attack_entity(self, request: AttackEntityRequest, ctx: RequestContext[AttackEntityRequest, AttackEntityResponse]) -> AttackEntityResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def interact_entity(self, request: InteractEntityRequest, ctx: RequestContext[InteractEntityRequest, InteractEntityResponse]) -> InteractEntityResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def swing_arm(self, request: SwingArmRequest, ctx: RequestContext[SwingArmRequest, SwingArmResponse]) -> SwingArmResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def respawn(self, request: RespawnRequest, ctx: RequestContext[RespawnRequest, RespawnResponse]) -> RespawnResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def go_to(self, request: GoToRequest, ctx: RequestContext[GoToRequest, PathfindProgress]) -> Iterator[PathfindProgress]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def stop_pathfinding(self, request: StopPathfindingRequest, ctx: RequestContext[StopPathfindingRequest, StopPathfindingResponse]) -> StopPathfindingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def acquire_bot_control(self, request: AcquireBotControlRequest, ctx: RequestContext[AcquireBotControlRequest, AcquireBotControlResponse]) -> AcquireBotControlResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def renew_bot_control(self, request: RenewBotControlRequest, ctx: RequestContext[RenewBotControlRequest, RenewBotControlResponse]) -> RenewBotControlResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def release_bot_control(self, request: ReleaseBotControlRequest, ctx: RequestContext[ReleaseBotControlRequest, ReleaseBotControlResponse]) -> ReleaseBotControlResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class BotLiveServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: BotLiveServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/soulfire.v1.BotLiveService/WatchBotEvents": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="WatchBotEvents",
                        service_name="soulfire.v1.BotLiveService",
                        input=WatchBotEventsRequest,
                        output=BotEvent,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch_bot_events,
                ),
                "/soulfire.v1.BotLiveService/SendChat": EndpointSync.unary(
                    method=MethodInfo(
                        name="SendChat",
                        service_name="soulfire.v1.BotLiveService",
                        input=SendChatRequest,
                        output=SendChatResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.send_chat,
                ),
                "/soulfire.v1.BotLiveService/GetBlock": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetBlock",
                        service_name="soulfire.v1.BotLiveService",
                        input=GetBlockRequest,
                        output=GetBlockResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_block,
                ),
                "/soulfire.v1.BotLiveService/FindBlocks": EndpointSync.unary(
                    method=MethodInfo(
                        name="FindBlocks",
                        service_name="soulfire.v1.BotLiveService",
                        input=FindBlocksRequest,
                        output=FindBlocksResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.find_blocks,
                ),
                "/soulfire.v1.BotLiveService/ListNearbyEntities": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNearbyEntities",
                        service_name="soulfire.v1.BotLiveService",
                        input=ListNearbyEntitiesRequest,
                        output=ListNearbyEntitiesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_nearby_entities,
                ),
                "/soulfire.v1.BotLiveService/DigBlock": EndpointSync.unary(
                    method=MethodInfo(
                        name="DigBlock",
                        service_name="soulfire.v1.BotLiveService",
                        input=DigBlockRequest,
                        output=DigBlockResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.dig_block,
                ),
                "/soulfire.v1.BotLiveService/PlaceBlock": EndpointSync.unary(
                    method=MethodInfo(
                        name="PlaceBlock",
                        service_name="soulfire.v1.BotLiveService",
                        input=PlaceBlockRequest,
                        output=PlaceBlockResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.place_block,
                ),
                "/soulfire.v1.BotLiveService/UseItem": EndpointSync.unary(
                    method=MethodInfo(
                        name="UseItem",
                        service_name="soulfire.v1.BotLiveService",
                        input=UseItemRequest,
                        output=UseItemResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.use_item,
                ),
                "/soulfire.v1.BotLiveService/ReleaseItem": EndpointSync.unary(
                    method=MethodInfo(
                        name="ReleaseItem",
                        service_name="soulfire.v1.BotLiveService",
                        input=ReleaseItemRequest,
                        output=ReleaseItemResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.release_item,
                ),
                "/soulfire.v1.BotLiveService/AttackEntity": EndpointSync.unary(
                    method=MethodInfo(
                        name="AttackEntity",
                        service_name="soulfire.v1.BotLiveService",
                        input=AttackEntityRequest,
                        output=AttackEntityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.attack_entity,
                ),
                "/soulfire.v1.BotLiveService/InteractEntity": EndpointSync.unary(
                    method=MethodInfo(
                        name="InteractEntity",
                        service_name="soulfire.v1.BotLiveService",
                        input=InteractEntityRequest,
                        output=InteractEntityResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.interact_entity,
                ),
                "/soulfire.v1.BotLiveService/SwingArm": EndpointSync.unary(
                    method=MethodInfo(
                        name="SwingArm",
                        service_name="soulfire.v1.BotLiveService",
                        input=SwingArmRequest,
                        output=SwingArmResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.swing_arm,
                ),
                "/soulfire.v1.BotLiveService/Respawn": EndpointSync.unary(
                    method=MethodInfo(
                        name="Respawn",
                        service_name="soulfire.v1.BotLiveService",
                        input=RespawnRequest,
                        output=RespawnResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.respawn,
                ),
                "/soulfire.v1.BotLiveService/GoTo": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="GoTo",
                        service_name="soulfire.v1.BotLiveService",
                        input=GoToRequest,
                        output=PathfindProgress,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.go_to,
                ),
                "/soulfire.v1.BotLiveService/StopPathfinding": EndpointSync.unary(
                    method=MethodInfo(
                        name="StopPathfinding",
                        service_name="soulfire.v1.BotLiveService",
                        input=StopPathfindingRequest,
                        output=StopPathfindingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stop_pathfinding,
                ),
                "/soulfire.v1.BotLiveService/AcquireBotControl": EndpointSync.unary(
                    method=MethodInfo(
                        name="AcquireBotControl",
                        service_name="soulfire.v1.BotLiveService",
                        input=AcquireBotControlRequest,
                        output=AcquireBotControlResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.acquire_bot_control,
                ),
                "/soulfire.v1.BotLiveService/RenewBotControl": EndpointSync.unary(
                    method=MethodInfo(
                        name="RenewBotControl",
                        service_name="soulfire.v1.BotLiveService",
                        input=RenewBotControlRequest,
                        output=RenewBotControlResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.renew_bot_control,
                ),
                "/soulfire.v1.BotLiveService/ReleaseBotControl": EndpointSync.unary(
                    method=MethodInfo(
                        name="ReleaseBotControl",
                        service_name="soulfire.v1.BotLiveService",
                        input=ReleaseBotControlRequest,
                        output=ReleaseBotControlResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.release_bot_control,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.BotLiveService"


class BotLiveServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def watch_bot_events(
        self,
        request: WatchBotEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[BotEvent]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="WatchBotEvents",
                service_name="soulfire.v1.BotLiveService",
                input=WatchBotEventsRequest,
                output=BotEvent,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def send_chat(
        self,
        request: SendChatRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SendChatResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendChat",
                service_name="soulfire.v1.BotLiveService",
                input=SendChatRequest,
                output=SendChatResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_block(
        self,
        request: GetBlockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetBlockResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBlock",
                service_name="soulfire.v1.BotLiveService",
                input=GetBlockRequest,
                output=GetBlockResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def find_blocks(
        self,
        request: FindBlocksRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> FindBlocksResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FindBlocks",
                service_name="soulfire.v1.BotLiveService",
                input=FindBlocksRequest,
                output=FindBlocksResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_nearby_entities(
        self,
        request: ListNearbyEntitiesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ListNearbyEntitiesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNearbyEntities",
                service_name="soulfire.v1.BotLiveService",
                input=ListNearbyEntitiesRequest,
                output=ListNearbyEntitiesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def dig_block(
        self,
        request: DigBlockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> DigBlockResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DigBlock",
                service_name="soulfire.v1.BotLiveService",
                input=DigBlockRequest,
                output=DigBlockResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def place_block(
        self,
        request: PlaceBlockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PlaceBlockResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PlaceBlock",
                service_name="soulfire.v1.BotLiveService",
                input=PlaceBlockRequest,
                output=PlaceBlockResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def use_item(
        self,
        request: UseItemRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> UseItemResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UseItem",
                service_name="soulfire.v1.BotLiveService",
                input=UseItemRequest,
                output=UseItemResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def release_item(
        self,
        request: ReleaseItemRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ReleaseItemResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseItem",
                service_name="soulfire.v1.BotLiveService",
                input=ReleaseItemRequest,
                output=ReleaseItemResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def attack_entity(
        self,
        request: AttackEntityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AttackEntityResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AttackEntity",
                service_name="soulfire.v1.BotLiveService",
                input=AttackEntityRequest,
                output=AttackEntityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def interact_entity(
        self,
        request: InteractEntityRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> InteractEntityResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InteractEntity",
                service_name="soulfire.v1.BotLiveService",
                input=InteractEntityRequest,
                output=InteractEntityResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def swing_arm(
        self,
        request: SwingArmRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> SwingArmResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SwingArm",
                service_name="soulfire.v1.BotLiveService",
                input=SwingArmRequest,
                output=SwingArmResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def respawn(
        self,
        request: RespawnRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RespawnResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Respawn",
                service_name="soulfire.v1.BotLiveService",
                input=RespawnRequest,
                output=RespawnResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def go_to(
        self,
        request: GoToRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[PathfindProgress]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="GoTo",
                service_name="soulfire.v1.BotLiveService",
                input=GoToRequest,
                output=PathfindProgress,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def stop_pathfinding(
        self,
        request: StopPathfindingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> StopPathfindingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StopPathfinding",
                service_name="soulfire.v1.BotLiveService",
                input=StopPathfindingRequest,
                output=StopPathfindingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def acquire_bot_control(
        self,
        request: AcquireBotControlRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AcquireBotControlResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AcquireBotControl",
                service_name="soulfire.v1.BotLiveService",
                input=AcquireBotControlRequest,
                output=AcquireBotControlResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def renew_bot_control(
        self,
        request: RenewBotControlRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> RenewBotControlResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RenewBotControl",
                service_name="soulfire.v1.BotLiveService",
                input=RenewBotControlRequest,
                output=RenewBotControlResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def release_bot_control(
        self,
        request: ReleaseBotControlRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> ReleaseBotControlResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ReleaseBotControl",
                service_name="soulfire.v1.BotLiveService",
                input=ReleaseBotControlRequest,
                output=ReleaseBotControlResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
