# Generated from soulfire/command.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .command_pb2 import CommandCompletionRequest, CommandCompletionResponse, CommandRequest, CommandResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class CommandService(Protocol):
    async def execute_command(self, request: CommandRequest, ctx: RequestContext[CommandRequest, CommandResponse]) -> CommandResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def tab_complete_command(self, request: CommandCompletionRequest, ctx: RequestContext[CommandCompletionRequest, CommandCompletionResponse]) -> CommandCompletionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class CommandServiceASGIApplication(ConnectASGIApplication[CommandService]):
    def __init__(
        self,
        service: CommandService | AsyncGenerator[CommandService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/soulfire.v1.CommandService/ExecuteCommand": Endpoint.unary(
                    method=MethodInfo(
                        name="ExecuteCommand",
                        service_name="soulfire.v1.CommandService",
                        input=CommandRequest,
                        output=CommandResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_command,
                ),
                "/soulfire.v1.CommandService/TabCompleteCommand": Endpoint.unary(
                    method=MethodInfo(
                        name="TabCompleteCommand",
                        service_name="soulfire.v1.CommandService",
                        input=CommandCompletionRequest,
                        output=CommandCompletionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.tab_complete_command,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.CommandService"


class CommandServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def execute_command(
        self,
        request: CommandRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> CommandResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteCommand",
                service_name="soulfire.v1.CommandService",
                input=CommandRequest,
                output=CommandResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def tab_complete_command(
        self,
        request: CommandCompletionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> CommandCompletionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TabCompleteCommand",
                service_name="soulfire.v1.CommandService",
                input=CommandCompletionRequest,
                output=CommandCompletionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class CommandServiceSync(Protocol):
    def execute_command(self, request: CommandRequest, ctx: RequestContext[CommandRequest, CommandResponse]) -> CommandResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def tab_complete_command(self, request: CommandCompletionRequest, ctx: RequestContext[CommandCompletionRequest, CommandCompletionResponse]) -> CommandCompletionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class CommandServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: CommandServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/soulfire.v1.CommandService/ExecuteCommand": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExecuteCommand",
                        service_name="soulfire.v1.CommandService",
                        input=CommandRequest,
                        output=CommandResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_command,
                ),
                "/soulfire.v1.CommandService/TabCompleteCommand": EndpointSync.unary(
                    method=MethodInfo(
                        name="TabCompleteCommand",
                        service_name="soulfire.v1.CommandService",
                        input=CommandCompletionRequest,
                        output=CommandCompletionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.tab_complete_command,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.CommandService"


class CommandServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def execute_command(
        self,
        request: CommandRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> CommandResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteCommand",
                service_name="soulfire.v1.CommandService",
                input=CommandRequest,
                output=CommandResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def tab_complete_command(
        self,
        request: CommandCompletionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> CommandCompletionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TabCompleteCommand",
                service_name="soulfire.v1.CommandService",
                input=CommandCompletionRequest,
                output=CommandCompletionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
