# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soulfire/download.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'soulfire/download.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from soulfire import common_pb2 as soulfire_dot_common__pb2
from soulfire import api_docs_pb2 as soulfire_dot_api__docs__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17soulfire/download.proto\x12\x0bsoulfire.v1\x1a\x15soulfire/common.proto\x1a\x17soulfire/api_docs.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\">\n\nHeaderPair\x12\x15\n\x03key\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x03key\x12\x19\n\x05value\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x05value\"\xd2\x01\n\x0f\x44ownloadRequest\x12.\n\x0binstance_id\x18\x01 \x01(\tB\r\xe0\x41\x02\xd2\xf3\x18\x06\n\x04uuidR\ninstanceId\x12\x1e\n\x03uri\x18\x02 \x01(\tB\x0c\xe0\x41\x02\xd2\xf3\x18\x05\n\x03uriR\x03uri\x12\x31\n\x07headers\x18\x03 \x03(\x0b\x32\x17.soulfire.v1.HeaderPairR\x07headers\x12\x32\n\x05proxy\x18\x04 \x01(\x0b\x32\x17.soulfire.v1.ProxyProtoH\x00R\x05proxy\x88\x01\x01\x42\x08\n\x06_proxy\"\x89\x01\n\x10\x44ownloadResponse\x12\x17\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x42\x03\xe0\x41\x02R\x04\x64\x61ta\x12\x36\n\x07headers\x18\x02 \x03(\x0b\x32\x17.soulfire.v1.HeaderPairB\x03\xe0\x41\x02R\x07headers\x12$\n\x0bstatus_code\x18\x03 \x01(\x05\x42\x03\xe0\x41\x02R\nstatusCode2\xfa\x01\n\x0f\x44ownloadService\x12\xe6\x01\n\x08\x44ownload\x12\x1c.soulfire.v1.DownloadRequest\x1a\x1d.soulfire.v1.DownloadResponse\"\x9c\x01\xca\xf3\x18\x62\n\x0c\x44ownload URL\x1a\x0c\x44OWNLOAD_URL\"\x08instance::Fetches remote content through the server\'s network stack.\x82\xd3\xe4\x93\x02\x30\"+/v1/instances/{instance_id}/downloads:fetch:\x01*B!\n\x1d\x63om.soulfiremc.grpc.generatedP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soulfire.download_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.soulfiremc.grpc.generatedP\001'
  _globals['_HEADERPAIR'].fields_by_name['key']._loaded_options = None
  _globals['_HEADERPAIR'].fields_by_name['key']._serialized_options = b'\340A\002'
  _globals['_HEADERPAIR'].fields_by_name['value']._loaded_options = None
  _globals['_HEADERPAIR'].fields_by_name['value']._serialized_options = b'\340A\002'
  _globals['_DOWNLOADREQUEST'].fields_by_name['instance_id']._loaded_options = None
  _globals['_DOWNLOADREQUEST'].fields_by_name['instance_id']._serialized_options = b'\340A\002\322\363\030\006\n\004uuid'
  _globals['_DOWNLOADREQUEST'].fields_by_name['uri']._loaded_options = None
  _globals['_DOWNLOADREQUEST'].fields_by_name['uri']._serialized_options = b'\340A\002\322\363\030\005\n\003uri'
  _globals['_DOWNLOADRESPONSE'].fields_by_name['data']._loaded_options = None
  _globals['_DOWNLOADRESPONSE'].fields_by_name['data']._serialized_options = b'\340A\002'
  _globals['_DOWNLOADRESPONSE'].fields_by_name['headers']._loaded_options = None
  _globals['_DOWNLOADRESPONSE'].fields_by_name['headers']._serialized_options = b'\340A\002'
  _globals['_DOWNLOADRESPONSE'].fields_by_name['status_code']._loaded_options = None
  _globals['_DOWNLOADRESPONSE'].fields_by_name['status_code']._serialized_options = b'\340A\002'
  _globals['_DOWNLOADSERVICE'].methods_by_name['Download']._loaded_options = None
  _globals['_DOWNLOADSERVICE'].methods_by_name['Download']._serialized_options = b'\312\363\030b\n\014Download URL\032\014DOWNLOAD_URL\"\010instance::Fetches remote content through the server\'s network stack.\202\323\344\223\0020\"+/v1/instances/{instance_id}/downloads:fetch:\001*'
  _globals['_HEADERPAIR']._serialized_start=151
  _globals['_HEADERPAIR']._serialized_end=213
  _globals['_DOWNLOADREQUEST']._serialized_start=216
  _globals['_DOWNLOADREQUEST']._serialized_end=426
  _globals['_DOWNLOADRESPONSE']._serialized_start=429
  _globals['_DOWNLOADRESPONSE']._serialized_end=566
  _globals['_DOWNLOADSERVICE']._serialized_start=569
  _globals['_DOWNLOADSERVICE']._serialized_end=819
# @@protoc_insertion_point(module_scope)
