# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soulfire/instance_live.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'soulfire/instance_live.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from soulfire import api_docs_pb2 as soulfire_dot_api__docs__pb2
from soulfire import bot_live_pb2 as soulfire_dot_bot__live__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csoulfire/instance_live.proto\x12\x0bsoulfire.v1\x1a\x17soulfire/api_docs.proto\x1a\x17soulfire/bot_live.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xda\x01\n\x13InstanceEventFilter\x12!\n\x0cinclude_chat\x18\x01 \x01(\x08R\x0bincludeChat\x12+\n\x11include_lifecycle\x18\x02 \x01(\x08R\x10includeLifecycle\x12?\n\nbot_events\x18\x03 \x01(\x0b\x32\x1b.soulfire.v1.BotEventFilterH\x00R\tbotEvents\x88\x01\x01\x12#\n\x07\x62ot_ids\x18\x04 \x03(\tB\n\xd2\xf3\x18\x06\n\x04uuidR\x06\x62otIdsB\r\n\x0b_bot_events\"\x8b\x01\n\x1aWatchInstanceEventsRequest\x12.\n\x0binstance_id\x18\x01 \x01(\tB\r\xe0\x41\x02\xd2\xf3\x18\x06\n\x04uuidR\ninstanceId\x12=\n\x06\x66ilter\x18\x02 \x01(\x0b\x32 .soulfire.v1.InstanceEventFilterB\x03\xe0\x41\x02R\x06\x66ilter\"\x8f\x02\n\rInstanceEvent\x12\x33\n\x0e\x62ot_profile_id\x18\x01 \x01(\tB\r\xe0\x41\x02\xd2\xf3\x18\x06\n\x04uuidR\x0c\x62otProfileId\x12\x19\n\x08\x62ot_name\x18\x02 \x01(\tR\x07\x62otName\x12/\n\x04\x63hat\x18\x03 \x01(\x0b\x32\x19.soulfire.v1.BotChatEventH\x00R\x04\x63hat\x12>\n\tlifecycle\x18\x04 \x01(\x0b\x32\x1e.soulfire.v1.BotLifecycleEventH\x00R\tlifecycle\x12\x34\n\tbot_event\x18\x05 \x01(\x0b\x32\x15.soulfire.v1.BotEventH\x00R\x08\x62otEventB\x07\n\x05\x65vent2\xa1\x02\n\x13InstanceLiveService\x12\x89\x02\n\x13WatchInstanceEvents\x12\'.soulfire.v1.WatchInstanceEventsRequest\x1a\x1a.soulfire.v1.InstanceEvent\"\xaa\x01\xca\xf3\x18\xa5\x01\n\x15Watch instance events\x1a\rREAD_BOT_INFO\"\x08instance23Opens a live event stream until the client cancels.:>Allocates server-side subscription resources for the instance.0\x01\x42!\n\x1d\x63om.soulfiremc.grpc.generatedP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soulfire.instance_live_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.soulfiremc.grpc.generatedP\001'
  _globals['_INSTANCEEVENTFILTER'].fields_by_name['bot_ids']._loaded_options = None
  _globals['_INSTANCEEVENTFILTER'].fields_by_name['bot_ids']._serialized_options = b'\322\363\030\006\n\004uuid'
  _globals['_WATCHINSTANCEEVENTSREQUEST'].fields_by_name['instance_id']._loaded_options = None
  _globals['_WATCHINSTANCEEVENTSREQUEST'].fields_by_name['instance_id']._serialized_options = b'\340A\002\322\363\030\006\n\004uuid'
  _globals['_WATCHINSTANCEEVENTSREQUEST'].fields_by_name['filter']._loaded_options = None
  _globals['_WATCHINSTANCEEVENTSREQUEST'].fields_by_name['filter']._serialized_options = b'\340A\002'
  _globals['_INSTANCEEVENT'].fields_by_name['bot_profile_id']._loaded_options = None
  _globals['_INSTANCEEVENT'].fields_by_name['bot_profile_id']._serialized_options = b'\340A\002\322\363\030\006\n\004uuid'
  _globals['_INSTANCELIVESERVICE'].methods_by_name['WatchInstanceEvents']._loaded_options = None
  _globals['_INSTANCELIVESERVICE'].methods_by_name['WatchInstanceEvents']._serialized_options = b'\312\363\030\245\001\n\025Watch instance events\032\rREAD_BOT_INFO\"\010instance23Opens a live event stream until the client cancels.:>Allocates server-side subscription resources for the instance.'
  _globals['_INSTANCEEVENTFILTER']._serialized_start=129
  _globals['_INSTANCEEVENTFILTER']._serialized_end=347
  _globals['_WATCHINSTANCEEVENTSREQUEST']._serialized_start=350
  _globals['_WATCHINSTANCEEVENTSREQUEST']._serialized_end=489
  _globals['_INSTANCEEVENT']._serialized_start=492
  _globals['_INSTANCEEVENT']._serialized_end=763
  _globals['_INSTANCELIVESERVICE']._serialized_start=766
  _globals['_INSTANCELIVESERVICE']._serialized_end=1055
# @@protoc_insertion_point(module_scope)
