# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soulfire/login.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'soulfire/login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from soulfire import api_docs_pb2 as soulfire_dot_api__docs__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14soulfire/login.proto\x12\x0bsoulfire.v1\x1a\x17soulfire/api_docs.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"4\n\x0cLoginRequest\x12$\n\x05\x65mail\x18\x01 \x01(\tB\x0e\xe0\x41\x02\xd2\xf3\x18\x07\n\x05\x65mailR\x05\x65mail\"\xda\x03\n\x14NextAuthFlowResponse\x12\x35\n\x0f\x61uth_flow_token\x18\x01 \x01(\tB\r\xe0\x41\x02\xd2\xf3\x18\x06\n\x04uuidR\rauthFlowToken\x12L\n\nemail_code\x18\x02 \x01(\x0b\x32+.soulfire.v1.NextAuthFlowResponse.EmailCodeH\x00R\temailCode\x12\x45\n\x07success\x18\x03 \x01(\x0b\x32).soulfire.v1.NextAuthFlowResponse.SuccessH\x00R\x07success\x12\x45\n\x07\x66\x61ilure\x18\x04 \x01(\x0b\x32).soulfire.v1.NextAuthFlowResponse.FailureH\x00R\x07\x66\x61ilure\x1a\x0b\n\tEmailCode\x1a$\n\x07Success\x12\x19\n\x05token\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x05token\x1at\n\x07\x46\x61ilure\x12M\n\x06reason\x18\x01 \x01(\x0e\x32\x30.soulfire.v1.NextAuthFlowResponse.Failure.ReasonB\x03\xe0\x41\x02R\x06reason\"\x1a\n\x06Reason\x12\x10\n\x0cINVALID_CODE\x10\x00\x42\x06\n\x04next\"b\n\x10\x45mailCodeRequest\x12\x35\n\x0f\x61uth_flow_token\x18\x01 \x01(\tB\r\xe0\x41\x02\xd2\xf3\x18\x06\n\x04uuidR\rauthFlowToken\x12\x17\n\x04\x63ode\x18\x02 \x01(\tB\x03\xe0\x41\x02R\x04\x63ode2\x98\x03\n\x0cLoginService\x12\xbd\x01\n\x05Login\x12\x19.soulfire.v1.LoginRequest\x1a!.soulfire.v1.NextAuthFlowResponse\"v\xca\xf3\x18^\n\x10Start login flow\"\x0cpublic.login:<Starts an email login flow and may send a verification code.\x82\xd3\xe4\x93\x02\x0e\"\t/v1/login:\x01*\x12\xc7\x01\n\tEmailCode\x12\x1d.soulfire.v1.EmailCodeRequest\x1a!.soulfire.v1.NextAuthFlowResponse\"x\xca\xf3\x18U\n\x11Verify email code\"\x0cpublic.login:2Completes the login flow and may issue an API JWT.\x82\xd3\xe4\x93\x02\x19\"\x14/v1/login/email-code:\x01*B!\n\x1d\x63om.soulfiremc.grpc.generatedP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soulfire.login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.soulfiremc.grpc.generatedP\001'
  _globals['_LOGINREQUEST'].fields_by_name['email']._loaded_options = None
  _globals['_LOGINREQUEST'].fields_by_name['email']._serialized_options = b'\340A\002\322\363\030\007\n\005email'
  _globals['_NEXTAUTHFLOWRESPONSE_SUCCESS'].fields_by_name['token']._loaded_options = None
  _globals['_NEXTAUTHFLOWRESPONSE_SUCCESS'].fields_by_name['token']._serialized_options = b'\340A\002'
  _globals['_NEXTAUTHFLOWRESPONSE_FAILURE'].fields_by_name['reason']._loaded_options = None
  _globals['_NEXTAUTHFLOWRESPONSE_FAILURE'].fields_by_name['reason']._serialized_options = b'\340A\002'
  _globals['_NEXTAUTHFLOWRESPONSE'].fields_by_name['auth_flow_token']._loaded_options = None
  _globals['_NEXTAUTHFLOWRESPONSE'].fields_by_name['auth_flow_token']._serialized_options = b'\340A\002\322\363\030\006\n\004uuid'
  _globals['_EMAILCODEREQUEST'].fields_by_name['auth_flow_token']._loaded_options = None
  _globals['_EMAILCODEREQUEST'].fields_by_name['auth_flow_token']._serialized_options = b'\340A\002\322\363\030\006\n\004uuid'
  _globals['_EMAILCODEREQUEST'].fields_by_name['code']._loaded_options = None
  _globals['_EMAILCODEREQUEST'].fields_by_name['code']._serialized_options = b'\340A\002'
  _globals['_LOGINSERVICE'].methods_by_name['Login']._loaded_options = None
  _globals['_LOGINSERVICE'].methods_by_name['Login']._serialized_options = b'\312\363\030^\n\020Start login flow\"\014public.login:<Starts an email login flow and may send a verification code.\202\323\344\223\002\016\"\t/v1/login:\001*'
  _globals['_LOGINSERVICE'].methods_by_name['EmailCode']._loaded_options = None
  _globals['_LOGINSERVICE'].methods_by_name['EmailCode']._serialized_options = b'\312\363\030U\n\021Verify email code\"\014public.login:2Completes the login flow and may issue an API JWT.\202\323\344\223\002\031\"\024/v1/login/email-code:\001*'
  _globals['_LOGINREQUEST']._serialized_start=125
  _globals['_LOGINREQUEST']._serialized_end=177
  _globals['_NEXTAUTHFLOWRESPONSE']._serialized_start=180
  _globals['_NEXTAUTHFLOWRESPONSE']._serialized_end=654
  _globals['_NEXTAUTHFLOWRESPONSE_EMAILCODE']._serialized_start=479
  _globals['_NEXTAUTHFLOWRESPONSE_EMAILCODE']._serialized_end=490
  _globals['_NEXTAUTHFLOWRESPONSE_SUCCESS']._serialized_start=492
  _globals['_NEXTAUTHFLOWRESPONSE_SUCCESS']._serialized_end=528
  _globals['_NEXTAUTHFLOWRESPONSE_FAILURE']._serialized_start=530
  _globals['_NEXTAUTHFLOWRESPONSE_FAILURE']._serialized_end=646
  _globals['_NEXTAUTHFLOWRESPONSE_FAILURE_REASON']._serialized_start=620
  _globals['_NEXTAUTHFLOWRESPONSE_FAILURE_REASON']._serialized_end=646
  _globals['_EMAILCODEREQUEST']._serialized_start=656
  _globals['_EMAILCODEREQUEST']._serialized_end=754
  _globals['_LOGINSERVICE']._serialized_start=757
  _globals['_LOGINSERVICE']._serialized_end=1165
# @@protoc_insertion_point(module_scope)
