# Generated from soulfire/plugin_stats.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .plugin_stats_pb2 import GetInstancePluginStatsRequest, GetInstancePluginStatsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class PluginStatsService(Protocol):
    async def get_instance_plugin_stats(self, request: GetInstancePluginStatsRequest, ctx: RequestContext[GetInstancePluginStatsRequest, GetInstancePluginStatsResponse]) -> GetInstancePluginStatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PluginStatsServiceASGIApplication(ConnectASGIApplication[PluginStatsService]):
    def __init__(
        self,
        service: PluginStatsService | AsyncGenerator[PluginStatsService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/soulfire.v1.PluginStatsService/GetInstancePluginStats": Endpoint.unary(
                    method=MethodInfo(
                        name="GetInstancePluginStats",
                        service_name="soulfire.v1.PluginStatsService",
                        input=GetInstancePluginStatsRequest,
                        output=GetInstancePluginStatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_instance_plugin_stats,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.PluginStatsService"


class PluginStatsServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_instance_plugin_stats(
        self,
        request: GetInstancePluginStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetInstancePluginStatsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstancePluginStats",
                service_name="soulfire.v1.PluginStatsService",
                input=GetInstancePluginStatsRequest,
                output=GetInstancePluginStatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class PluginStatsServiceSync(Protocol):
    def get_instance_plugin_stats(self, request: GetInstancePluginStatsRequest, ctx: RequestContext[GetInstancePluginStatsRequest, GetInstancePluginStatsResponse]) -> GetInstancePluginStatsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PluginStatsServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: PluginStatsServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/soulfire.v1.PluginStatsService/GetInstancePluginStats": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetInstancePluginStats",
                        service_name="soulfire.v1.PluginStatsService",
                        input=GetInstancePluginStatsRequest,
                        output=GetInstancePluginStatsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_instance_plugin_stats,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.PluginStatsService"


class PluginStatsServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def get_instance_plugin_stats(
        self,
        request: GetInstancePluginStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> GetInstancePluginStatsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstancePluginStats",
                service_name="soulfire.v1.PluginStatsService",
                input=GetInstancePluginStatsRequest,
                output=GetInstancePluginStatsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
