# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soulfire/proxy-check.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'soulfire/proxy-check.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from soulfire import common_pb2 as soulfire_dot_common__pb2
from soulfire import api_docs_pb2 as soulfire_dot_api__docs__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asoulfire/proxy-check.proto\x12\x0bsoulfire.v1\x1a\x15soulfire/common.proto\x1a\x17soulfire/api_docs.proto\x1a\x1fgoogle/api/field_behavior.proto\"w\n\x11ProxyCheckRequest\x12.\n\x0binstance_id\x18\x01 \x01(\tB\r\xe0\x41\x02\xd2\xf3\x18\x06\n\x04uuidR\ninstanceId\x12\x32\n\x05proxy\x18\x02 \x03(\x0b\x32\x17.soulfire.v1.ProxyProtoB\x03\xe0\x41\x02R\x05proxy\"\xa6\x01\n\x18ProxyCheckResponseSingle\x12\x32\n\x05proxy\x18\x01 \x01(\x0b\x32\x17.soulfire.v1.ProxyProtoB\x03\xe0\x41\x02R\x05proxy\x12\x19\n\x05valid\x18\x02 \x01(\x08\x42\x03\xe0\x41\x02R\x05valid\x12\x1d\n\x07latency\x18\x03 \x01(\x05\x42\x03\xe0\x41\x02R\x07latency\x12\x1c\n\x07real_ip\x18\x04 \x01(\tB\x03\xe0\x41\x02R\x06realIp\"\x0f\n\rProxyCheckEnd\"\x8d\x01\n\x12ProxyCheckResponse\x12?\n\x06single\x18\x04 \x01(\x0b\x32%.soulfire.v1.ProxyCheckResponseSingleH\x00R\x06single\x12.\n\x03\x65nd\x18\x05 \x01(\x0b\x32\x1a.soulfire.v1.ProxyCheckEndH\x00R\x03\x65ndB\x06\n\x04\x64\x61ta2\xd3\x01\n\x11ProxyCheckService\x12\xbd\x01\n\x05\x43heck\x12\x1e.soulfire.v1.ProxyCheckRequest\x1a\x1f.soulfire.v1.ProxyCheckResponse\"q\xca\xf3\x18m\n\rCheck proxies\x1a\x0b\x43HECK_PROXY\"\x08instance2\x10Server streaming:3Streams proxy-check results as each proxy finishes.0\x01\x42!\n\x1d\x63om.soulfiremc.grpc.generatedP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soulfire.proxy_check_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.soulfiremc.grpc.generatedP\001'
  _globals['_PROXYCHECKREQUEST'].fields_by_name['instance_id']._loaded_options = None
  _globals['_PROXYCHECKREQUEST'].fields_by_name['instance_id']._serialized_options = b'\340A\002\322\363\030\006\n\004uuid'
  _globals['_PROXYCHECKREQUEST'].fields_by_name['proxy']._loaded_options = None
  _globals['_PROXYCHECKREQUEST'].fields_by_name['proxy']._serialized_options = b'\340A\002'
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['proxy']._loaded_options = None
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['proxy']._serialized_options = b'\340A\002'
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['valid']._loaded_options = None
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['valid']._serialized_options = b'\340A\002'
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['latency']._loaded_options = None
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['latency']._serialized_options = b'\340A\002'
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['real_ip']._loaded_options = None
  _globals['_PROXYCHECKRESPONSESINGLE'].fields_by_name['real_ip']._serialized_options = b'\340A\002'
  _globals['_PROXYCHECKSERVICE'].methods_by_name['Check']._loaded_options = None
  _globals['_PROXYCHECKSERVICE'].methods_by_name['Check']._serialized_options = b'\312\363\030m\n\rCheck proxies\032\013CHECK_PROXY\"\010instance2\020Server streaming:3Streams proxy-check results as each proxy finishes.'
  _globals['_PROXYCHECKREQUEST']._serialized_start=124
  _globals['_PROXYCHECKREQUEST']._serialized_end=243
  _globals['_PROXYCHECKRESPONSESINGLE']._serialized_start=246
  _globals['_PROXYCHECKRESPONSESINGLE']._serialized_end=412
  _globals['_PROXYCHECKEND']._serialized_start=414
  _globals['_PROXYCHECKEND']._serialized_end=429
  _globals['_PROXYCHECKRESPONSE']._serialized_start=432
  _globals['_PROXYCHECKRESPONSE']._serialized_end=573
  _globals['_PROXYCHECKSERVICE']._serialized_start=576
  _globals['_PROXYCHECKSERVICE']._serialized_end=787
# @@protoc_insertion_point(module_scope)
